name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          XDEBUG_MODE: coverage

      - name: Run PHPStan
        run: vendor/bin/phpstan --configuration=phpstan.neon
