name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php-version: [8.1, 8.2, 8.3]

    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer:v2
          extensions: mbstring, json

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --dev --optimize-autoloader

      - name: Execute tests
        run: php vendor/bin/phpunit
        env:
          XDEBUG_MODE: coverage

      - name: Run PHPStan
        run: |
          echo "Running PHPStan analysis..."
          php vendor/bin/phpstan analyse --configuration=phpstan.neon --verbose --error-format=github --no-progress
